development:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  # TODO: read from env var. Use this to create a new one: SecureRandom.hex(32)
  encryption_key: 8ee020a02d0042901a280ea97bac491719e28a0add89b67f60c75d0b4fa338de

test:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  encryption_key: 8ee020a02d0042901a280ea97bac491719e28a0add89b67f60c75d0b4fa338de

staging:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  encryption_key: 8ee020a02d0042901a280ea97bac491719e28a0add89b67f60c75d0b4fa338de

production:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  encryption_key: 8ee020a02d0042901a280ea97bac491719e28a0add89b67f60c75d0b4fa338de

